export const SESSION_RESTORING = "SESSION_RESTORING";
export const SESSION_LOADING = "SESSION_LOADING";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_ERROR = "SESSION_ERROR";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const SESSION_OTP_SENT = "SESSION_OTP_SENT";

export const ONB_ADD_BASIC_INFO = "ONB_ADD_BASIC_INFO";
export const ONB_ADD_PROFILE_TYPE = "ONB_ADD_PROFILE_TYPE";
export const ONB_RMV_EXAM = "ONB_RMV_EXAM";
export const ONB_UPS_EXAM = "ONB_UPS_EXAM";
export const ONB_ADD_PROFESSION = "ONB_ADD_PROFESSION";
export const ONB_ADD_INSTITUTION = "ONB_ADD_INSTITUTION";
export const ONB_UPD_DB = "ONB_UPD_DB";
export const ONB_ERROR = "ONB_ERROR";
export const ONB_FETCH_FROM_DB = "ONB_FETCH_FROM_DB";

export const MD_FETCH_EXAM_LIST = "MD_FETCH_EXAM_LIST";
